
custom:
  datasourceKey: hrc
  modulueName: process
  tableNames:
    - base
  projectPosition: /

common:
  method: YML_CONFIG
  datasourceType: mysql
  author: shishuai04
  email: shishuai04@baidu.com
  templateList:
    - templateName: Entity.java.vm
      templatePosition: template/Entity.java.vm
      templateFileName: Entity
      templateSuffix: .java
      existReplace: 1
      tableNameRex: ${moduleName}
      modulePackage: com.shishuai.${moduleName}.entity
      projectCodeRelativePosition: src\main\java
      moduleNameShow: 1
    - templateName: Dao.java.vm
      templatePosition: template/Dao.java.vm
      templateFileName: Mapper
      templateSuffix: .java
      existReplace: 1
      tableNameRex: ${moduleName}
      modulePackage: com.shishuai.${moduleName}.Dao
      projectCodeRelativePosition: src\main\java
      moduleNameShow: 1
