server:
  port: 8888
mybatis-plus:
  mapper-locations: classpath*:sql/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.person.quick.entity
  global-config:
    #是否自动刷新 Mapper对应的 XML文件，无需重启
    refresh: true
    db-config:
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      #逻辑删除配置（如果你的默认值和mp默认的一样,该配置可无）
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#spring:
#  datasource:
#    dynamic:
#      primary: base
#      datasource:
#        base:
#          url: jdbc:mysql://120.48.31.80:3306/base?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&connectTimeout=2000&autoReconnect=true&maxReconnects=5&serverTimezone=Asia/Shanghai
#          username: ss
#          password: 123
#          driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: info

#debug: true
spring:
  datasource:
    dynamic:
      primary: base
      datasource:
        base:
          url: jdbc:h2:mem:base;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
          driver-class-name: org.h2.Driver
          username: root
          password: 123
    schema: classpath:h2/base-schema.sql
    data: classpath:h2/base-data.sql