server:
  port: 8888
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

spring:
  datasource:
    dynamic:
      primary: base
      datasource:
        base:
          url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&connectTimeout=2000&autoReconnect=true&maxReconnects=5&serverTimezone=Asia/Shanghai
          username: root
          password: 123
          driver-class-name: com.mysql.cj.jdbc.Driver

