
#spring:
#  datasource:
#    dynamic:
#      primary: base
#      datasource:
#        base:
#          url: jdbc:mysql://120.48.31.80:3306/hrc?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&connectTimeout=2000&autoReconnect=true&maxReconnects=5&serverTimezone=Asia/Shanghai
#          username: ss
#          password: 123
#          driver-class-name: com.mysql.cj.jdbc.Driver

custom:
  dataSourceKey: hrc
  modulueName: process
  tableNames:
    - base_process_time
    - base_transport_containers
  projectPosition: /Users/ss/Desktop/aiib-medical

common:
  method: YML_CONFIG
  datasourceType: mysql
  author: shishuai04
  email: shishuai04@baidu.com
  templateList:
    - templateName: Entity.java.vm
      templatePosition: template/Entity.java.vm
      templateKey: Entity
      templateFileName: Entity
      templateSuffix: .java
      existReplace: 0
      tableNameRex: ${moduleName}
      modulePackage: com.baidu.aiig.medical.famg.data.famg.model
      projectCodeRelativePosition: medical-famg-dao/src/main/java
      moduleNameShow: 1
    - templateName: Dao.java.vm
      templatePosition: template/Dao.java.vm
      templateKey: Mapper
      templateFileName: Mapper
      templateSuffix: .java
      existReplace: 0
      tableNameRex: ${moduleName}
      modulePackage: com.baidu.aiig.medical.famg.data.famg.mapper
      projectCodeRelativePosition: medical-famg-dao/src/main/java
      moduleNameShow: 1
    - templateName: Dao.xml.vm
      templatePosition: template/Dao.xml.vm
      templateKey: MapperXml
      templateFileName: Mapper
      templateSuffix: .xml
      existReplace: 0
      tableNameRex: ${moduleName}
      modulePackage: famg
      projectCodeRelativePosition: medical-famg-dao/src/main/resources/sqlmap
      moduleNameShow: 1
    - templateName: Controller.java.vm
      templatePosition: template/Controller.java.vm
      templateKey: Controller
      templateFileName: Controller
      templateSuffix: .java
      existReplace: 0
      tableNameRex: ${moduleName}
      modulePackage: com.baidu.aiig.medical.famg.web.controller.${moduleName}
      projectCodeRelativePosition: famg/src/main/java
      moduleNameShow: 1
    - templateName: Service.java.vm
      templatePosition: template/Service.java.vm
      templateKey: Service
      templateFileName: Service
      templateSuffix: .java
      existReplace: 0
      tableNameRex: ${moduleName}
      modulePackage: com.baidu.aiig.medical.famg.data.famg.service.${moduleName}
      projectCodeRelativePosition: medical-famg-dao/src/main/java
      moduleNameShow: 1
    - templateName: ServiceImpl.java.vm
      templatePosition: template/ServiceImpl.java.vm
      templateKey: ServiceImpl
      templateFileName: ServiceImpl
      templateSuffix: .java
      existReplace: 0
      tableNameRex: ${moduleName}
      modulePackage: com.baidu.aiig.medical.famg.data.famg.service.impl.${moduleName}
      projectCodeRelativePosition:  medical-famg-dao/src/main/java
      moduleNameShow: 1
